HomeWorkfirst/Models/CustomerDetailsView.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeWorkfirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerDetailsView
    {
        public int ID { get; set; }
        public string 客戶名稱 { get; set; }
        public Nullable<int> 聯絡人數量 { get; set; }
        public Nullable<int> 銀行帳戶數量 { get; set; }
    }
}

HomeWorkfirst/Models/客戶資料.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeWorkfirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 客戶資料
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 客戶資料()
        {
            this.客戶銀行資訊 = new HashSet<客戶銀行資訊>();
            this.客戶聯絡人 = new HashSet<客戶聯絡人>();
        }
    
        public int Id { get; set; }
        public string 客戶名稱 { get; set; }
        public string 統一編號 { get; set; }
        public string 電話 { get; set; }
        public string 傳真 { get; set; }
        public string 地址 { get; set; }
        public string Email { get; set; }
        public bool 是否已刪除 { get; set; }
        public string 客戶分類 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<客戶銀行資訊> 客戶銀行資訊 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<客戶聯絡人> 客戶聯絡人 { get; set; }
    }
}

HomeWorkfirst/Controllers/客戶資料Controller.cs
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using HomeWorkfirst.Models;
using MvcPaging;
using HomeWorkfirst.Models.ViewModel;
using System.Data.Entity.Validation;
using System.Data.Entity.Infrastructure;
using System;

namespace HomeWorkfirst.Controllers
{
    [HandleError(ExceptionType = typeof(DbEntityValidationException), View = "Error_DbEntityValidationException")]
    public class 客戶資料Controller : BaseController
    {
        // private 客戶資料Entities db = new 客戶資料Entities();

        客戶資料Repository repo = RepositoryHelper.Get客戶資料Repository();

        /// <summary> 每頁筆數 </summary>
        int PageSize = 10;

        public ActionResult Index(客戶資料VM search, int? page)
        {
            ViewBag.客戶分類 = repo.Get客戶分類下拉選單列表();
            var data = repo.Get客戶資料列表所有資料( search );

            int currentPageIndex = page.HasValue ? page.Value - 1 : 0;
            return View(data.ToPagedList(currentPageIndex, PageSize));
        }

        /// <summary> 客戶資料檢視表 </summary>
        /// <returns></returns>
        public ActionResult CustomerDetails()
        {
            客戶資料Entities db = new 客戶資料Entities();
            var 客戶資料檢視表 = db.CustomerDetailsView;
            return View(客戶資料檢視表);
        }

        // GET: 客戶銀行資訊/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            客戶資料聯絡人明細VM 客戶明細 = repo.取得客戶聯絡人清單(id.Value);
            if (客戶明細 == null)
            {
                return HttpNotFound();
            }
            return View(客戶明細);
        }

        // GET: 客戶資料/Create
        public ActionResult Create()
        {
            ViewBag.客戶分類 = repo.Get客戶分類下拉選單列表();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [HandleError(ExceptionType = typeof(DbUpdateException), View = "Error_DbUpdateException")]
        public ActionResult Create(客戶資料 客戶資料)
        {
            if ( ModelState.IsValid ) {
                repo.Add(客戶資料);
                repo.UnitOfWork.Commit();
                return RedirectToAction("Index");
            }
            return View( 客戶資料 );
        }

        // GET: 客戶資料/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.客戶分類 = repo.Get客戶分類下拉選單列表();
            var data = repo.Get單筆資料ByID(id.Value);
            if (data == null) {
                return HttpNotFound();
            }
            return View(data);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(客戶資料 客戶資料)
        {
            if ( ModelState.IsValid ) {
                repo.Update(客戶資料);
                repo.UnitOfWork.Commit();
                return RedirectToAction("Index");
            }
            return View(客戶資料);
        }

        // POST: 客戶資料/Delete/5
        public ActionResult Delete(int id)
        {
            客戶資料 客戶資料 = repo.Get單筆資料ByID(id);
            repo.Delete(客戶資料);
            repo.UnitOfWork.Commit();
            return RedirectToAction("Index");
        }


        [HttpPost]
        public ActionResult BatchUpdate(BatchUpdateVM[] items)
        {
            if (ModelState.IsValid) {
                foreach (var item in items) {
                    var prod = repo.取得客戶聯絡人資料(item.Id);
                    prod.職稱 = item.職稱;
                    prod.電話 = item.電話;
                    prod.手機 = item.手機;
                }
                repo.UnitOfWork.Context.Configuration.ValidateOnSaveEnabled = false;
                repo.UnitOfWork.Commit();

                return RedirectToAction("Details", new { id = items.FirstOrDefault().客戶Id } );
            }
            return View("Details", items);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing) {
                repo.UnitOfWork.Context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HomeWorkfirst/Views/客戶資料/Create.cshtml
@model HomeWorkfirst.Models.客戶資料

@{
    ViewBag.Title = "新增客戶資料";
}

<h2>新增客戶資料</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.客戶名稱, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.客戶名稱, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.客戶名稱, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.客戶分類, "客戶分類", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("客戶分類", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.客戶分類, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.統一編號, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.統一編號, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.統一編號, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.電話, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.電話, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.電話, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.傳真, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.傳真, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.傳真, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.地址, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.地址, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.地址, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("回到客戶資料列表", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HomeWorkfirst/Views/客戶資料/CustomerDetails.cshtml
@model IEnumerable<HomeWorkfirst.Models.CustomerDetailsView>

@{
    ViewBag.Title = "CustomerDetails";
}

<h2 style="padding:5px 0px 5px 0px;text-align:center;">客戶資料檢視表</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.客戶名稱)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.聯絡人數量)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.銀行帳戶數量)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.客戶名稱)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.聯絡人數量)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.銀行帳戶數量)
        </td>
    </tr>
}

</table>

HomeWorkfirst/Views/客戶資料/Details.cshtml
@model HomeWorkfirst.Models.ViewModel.客戶資料聯絡人明細VM

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>客戶資料</h4>
    <hr />
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.客戶資料.客戶名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.客戶資料.客戶名稱)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.客戶資料.客戶分類)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.客戶資料.客戶分類)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.客戶資料.統一編號)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.客戶資料.統一編號)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.客戶資料.電話)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.客戶資料.電話)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.客戶資料.傳真)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.客戶資料.傳真)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.客戶資料.地址)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.客戶資料.地址)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.客戶資料.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.客戶資料.Email)
        </dd>
    </dl>
</div>
@using (Html.BeginForm("BatchUpdate","客戶資料"))
{
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.客戶聯絡人.FirstOrDefault().職稱)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.客戶聯絡人.FirstOrDefault().姓名)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.客戶聯絡人.FirstOrDefault().Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.客戶聯絡人.FirstOrDefault().手機)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.客戶聯絡人.FirstOrDefault().電話)
        </th>
    </tr>
    @{
        var items = Model.客戶聯絡人.ToArray();
    }
    @for (var i = 0; i < items.Length; i++)
    {
        <tr>
            @Html.HiddenFor(modelItem => items[i].Id)
            @Html.HiddenFor(modelItem => items[i].客戶Id)
            <td>
                @Html.EditorFor(modelItem => items[i].職稱)
            </td>
            <td>
                @Html.DisplayFor(modelItem => items[i].姓名)
            </td>
            <td>
                @Html.DisplayFor(modelItem => items[i].Email)
            </td>
            <td>
                @Html.EditorFor(modelItem => items[i].手機)
            </td>
            <td>
                @Html.EditorFor(modelItem => items[i].電話)
            </td>
        </tr>
    }
</table>
    <button>批次更新</button>
}

HomeWorkfirst/Views/客戶資料/Edit.cshtml
@model HomeWorkfirst.Models.客戶資料

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>客戶資料</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.客戶名稱, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.客戶名稱, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.客戶名稱, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.客戶分類, "客戶分類", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("客戶分類", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.客戶分類, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.統一編號, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.統一編號, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.統一編號, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.電話, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.電話, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.電話, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.傳真, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.傳真, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.傳真, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.地址, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.地址, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.地址, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("回到客戶資料列表", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HomeWorkfirst/Views/客戶資料/Index.cshtml
@model IPagedList<HomeWorkfirst.Models.客戶資料>

@{
    ViewBag.Title = "客戶資料列表";
}

<h2 style="padding:5px 0px 5px 0px;text-align:center;">客戶資料列表</h2>

<p>
    @Html.ActionLink("新增客戶資料", "Create")
    @Html.ActionLink("客戶資料檢視表", "CustomerDetails", null, new { htmlAttributes = new { @style = "text-align:right;" } })

    @using (Html.BeginForm("Index", "客戶資料")) {
        <input type="search" name="keyword" placeholder="請輸入關鍵字" value="" />
        @Html.DropDownList("客戶分類", null, htmlAttributes: new { @class = "form-control" })
        <button>查詢</button>
    }

</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().客戶名稱)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().客戶分類)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().統一編號)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().電話)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().傳真)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().地址)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Email)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.客戶名稱)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.客戶分類)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.統一編號)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.電話)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.傳真)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.地址)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }
</table>
<div class="pager">
    @Html.Pager(Model.PageSize, Model.PageNumber, Model.TotalItemCount)
</div>